version: '3'

services:
    screen:
        build: .
        command: npm start
        container_name: login
        environment:
            - VUE_APP_REDIRECT_URL=https://google.com
            - NODE_ENV=development #change tis to production when running outside here
            - API_URL=http://localhost:4000
        ports:
            - "80:8080"
